[문제] xor를 logistic regression classifier를 이용해서 프로그램을 생성하세요.
```
000
011
101
110
```


In [63]:
import tensorflow as tf
import numpy as np

x_data = np.array([[0,0], [0,1], [1,0], [1,1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]],dtype=np.float32)

x = tf.placeholder(tf.float32, shape=[None, 2])
y = tf.placeholder(tf.float32, shape=[None, 1])

# input
w_1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
b_1 = tf.Variable(tf.random_normal([1]), name='bias1')
hp_1 = tf.sigmoid(tf.matmul(x, w_1)+b_1)

# hidden layer
w_2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
b_2 = tf.Variable(tf.random_normal([1]), name='bias2')
hp_2 = tf.sigmoid(tf.matmul(hp_1,w_2)+b_2)

cost = -tf.reduce_mean(y*tf.log(hp_2)+(1-y)*tf.log(1-hp_2)) # cross entropy cost function

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
predict = tf.cast(hp_2 > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict, y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        cost_val,_ = sess.run([cost, train], feed_dict={x:x_data, y:y_data})
        if step%1000 == 0:
            print(step, cost_val)
    h,c,a = sess.run([hp_2, predict, accuracy], feed_dict={x:x_data, y:y_data})
    print("hypothesis:", h)
    print("predict:", h)
    print("acuraccy:", a)

0 1.2610717
1000 0.65117455
2000 0.5679742
3000 0.48415333
4000 0.23172247
5000 0.11469449
6000 0.073206976
7000 0.053081132
8000 0.041400976
9000 0.03383339
10000 0.02855461
11000 0.024672981
12000 0.02170384
13000 0.019362038
14000 0.017469412
15000 0.015909005
16000 0.01460104
17000 0.013489279
18000 0.012532947
19000 0.011701801
20000 0.010972885
hypothesis: [[0.00966258]
 [0.9872044 ]
 [0.9873998 ]
 [0.00858376]]
predict: [[0.00966258]
 [0.9872044 ]
 [0.9873998 ]
 [0.00858376]]
acuraccy: 1.0


In [70]:
import tensorflow as tf
import numpy as np

x_data = np.array([[0,0], [0,1], [1,0], [1,1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]],dtype=np.float32)

x = tf.placeholder(tf.float32, shape=[None, 2])
y = tf.placeholder(tf.float32, shape=[None, 1])

# input
w_1 = tf.Variable(tf.random_normal([2, 5]), name='weight1')
b_1 = tf.Variable(tf.random_normal([5], seed=0), name='bias1')
layer_1 = tf.sigmoid(tf.matmul(x, w_1)+b_1)

# hidden layer
w_2 = tf.Variable(tf.random_normal([5, 4]), name='weight2')
b_2 = tf.Variable(tf.random_normal([4]), name='bias2')
layer_2 = tf.sigmoid(tf.matmul(layer_1,w_2)+b_2)

# hidden layer
w_3 = tf.Variable(tf.random_normal([4, 4]), name='weight3')
b_3 = tf.Variable(tf.random_normal([4]), name='bias3')
layer_3 = tf.sigmoid(tf.matmul(layer_2,w_3)+b_3)

# output layer
w_4 = tf.Variable(tf.random_normal([4, 1]), name='weight4')
b_4 = tf.Variable(tf.random_normal([1]), name='bias4')
hp = tf.sigmoid(tf.matmul(layer_3,w_4)+b_4)

cost = -tf.reduce_mean(y*tf.log(hp)+(1-y)*tf.log(1-hp)) # cross entropy cost function

train = tf.train.GradientDescentOptimizer(learning_rate=0.05).minimize(cost)
predict = tf.cast(hp > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict, y), dtype=tf.float32))

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(20001):
    sess.run(train,feed_dict={x:x_data, y:y_data})
    if step%1000 == 0:
        print(step, cost_val)
h,c,a = sess.run([hp, predict, accuracy], feed_dict={x:x_data, y:y_data})
print("hypothesis:", h)
print("predict:", h)
print("acuraccy:", a)

0 0.010972885
1000 0.010972885
2000 0.010972885
3000 0.010972885
4000 0.010972885
5000 0.010972885
6000 0.010972885
7000 0.010972885
8000 0.010972885
9000 0.010972885
10000 0.010972885
11000 0.010972885
12000 0.010972885
13000 0.010972885
14000 0.010972885
15000 0.010972885
16000 0.010972885
17000 0.010972885
18000 0.010972885
19000 0.010972885
20000 0.010972885
hypothesis: [[0.00258899]
 [0.9977431 ]
 [0.99729174]
 [0.00306805]]
predict: [[0.00258899]
 [0.9977431 ]
 [0.99729174]
 [0.00306805]]
acuraccy: 1.0


In [1]:
# binary classification
import tensorflow as tf
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x = tf.placeholder(tf.float32, shape=[None, 2])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hp = tf.sigmoid(tf.matmul(x,w)+b)

# logistic cost function
cost = -tf.reduce_mean(y*tf.log(hp) + (1-y)*tf.log(1-hp))

In [2]:
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
predict = tf.cast(hp > 0.5, dtype=tf.float32) # tf.cast:  조건문과 같은 역할
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict, y), dtype=tf.float32))

In [3]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={x:x_data,y:y_data})
        if step%500 == 0:
            print(step, cost_val)
    h,c,a = sess.run([hp, predict, accuracy], feed_dict={x:x_data, y:y_data})
    print("hypothesis:", h)
    print("predict:", h)
    print("acuraccy:", a)

0 1.020004
500 0.6254851
1000 0.53849113
1500 0.48663878
2000 0.4443854
2500 0.40762612
3000 0.3752532
3500 0.34669113
4000 0.32147452
4500 0.29918048
5000 0.27942523
5500 0.26186785
6000 0.24621014
6500 0.23219548
7000 0.21960355
7500 0.20824671
8000 0.19796515
8500 0.18862319
9000 0.18010479
9500 0.17231101
10000 0.1651572
hypothesis: [[0.03759236]
 [0.16720788]
 [0.33613726]
 [0.76743823]
 [0.9304502 ]
 [0.9771566 ]]
predict: [[0.03759236]
 [0.16720788]
 [0.33613726]
 [0.76743823]
 [0.9304502 ]
 [0.9771566 ]]
acuraccy: 1.0


In [86]:
#multi classification (softmax classifier)
import numpy as np
xy = np.loadtxt('data/train.txt', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

x = tf.placeholder(tf.float32, [None, 3])
y = tf.placeholder(tf.int32, [None, 1])

y_one_hot = tf.one_hot(y,3)
y_one_hot = tf.reshape(y_one_hot, [-1,3])

w = tf.Variable(tf.random_normal([3,3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

logits = tf.matmul(x,w) + b
hp = tf.nn.softmax(logits)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_one_hot))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
prediction = tf.argmax(hp, 1)
correct_prediction = tf.equal(prediction, tf.argmax(y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    sess.run(train, feed_dict={x:x_data, y:y_data})
    if step%100==0:
        loss, acc = sess.run([cost, accuracy], feed_dict={x:x_data, y:y_data})
        print('Step:', step)
        print('Loss:', loss)
        print('Acc:', acc)
'''
a1 = tf.Variable([0.1, 0.3, 0.5])
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(tf.argmax(a1)))
print(sess.run(tf.argmin(a1)))
sess.close()
'''
a = sess.run(hp, feed_dict={x:[[1,2,1]]})
print(a, sess.run(tf.argmax(a, 1)))

b = sess.run(hp, feed_dict={x:[[1,7,7]]})
print(b, sess.run(tf.argmax(b, 1)))

c = sess.run(hp, feed_dict={x:[[1,4, 5]]})
print(b, sess.run(tf.argmax(c, 1)))

Step: 0
Loss: 5.8398986
Acc: 0.5
Step: 100
Loss: 0.7051436
Acc: 0.5
Step: 200
Loss: 0.60350156
Acc: 0.625
Step: 300
Loss: 0.54488754
Acc: 0.875
Step: 400
Loss: 0.5029661
Acc: 1.0
Step: 500
Loss: 0.47010916
Acc: 1.0
Step: 600
Loss: 0.44311112
Acc: 1.0
Step: 700
Loss: 0.42028368
Acc: 1.0
Step: 800
Loss: 0.40059984
Acc: 1.0
Step: 900
Loss: 0.38337386
Acc: 1.0
Step: 1000
Loss: 0.3681194
Acc: 1.0
Step: 1100
Loss: 0.35447738
Acc: 1.0
Step: 1200
Loss: 0.3421739
Acc: 1.0
Step: 1300
Loss: 0.33099544
Acc: 1.0
Step: 1400
Loss: 0.32077402
Acc: 1.0
Step: 1500
Loss: 0.31137347
Acc: 1.0
Step: 1600
Loss: 0.30268365
Acc: 1.0
Step: 1700
Loss: 0.2946133
Acc: 1.0
Step: 1800
Loss: 0.28708738
Acc: 1.0
Step: 1900
Loss: 0.2800425
Acc: 1.0
Step: 2000
Loss: 0.27342537
Acc: 1.0
[[9.9800473e-01 1.9948815e-03 3.3908634e-07]] [0]
[[1.6775414e-04 8.4307253e-02 9.1552502e-01]] [2]
[[1.6775414e-04 8.4307253e-02 9.1552502e-01]] [1]
